num_experts: 8
top_k_experts: 2
gate_bias: false

xlstm_config:
  vocab_size: 32_000
  context_length: 256
  num_blocks: 12
  embedding_dim: 960

  mlstm_block:
    mlstm:
      conv1d_kernel_size: 4
      qkv_proj_blocksize: 32
      num_heads: 16

  slstm_block:
    slstm:
      backend: "vanilla"
      num_heads: 16
      conv1d_kernel_size: 4
      bias_init: "powerlaw_blockdependent"

    feedforward:
      proj_factor: 1.7
      act_fn: "gelu"
